<a href="https://colab.research.google.com/github/hsallrounder/Neural-Networks-Workshop-2023/blob/main/adaline__1_Neural_Networks_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class CustomAdaline(object):

    

    def __init__(self, n_iterations=100, random_state=1, learning_rate=0.01):

        self.n_iterations = n_iterations

        self.random_state = random_state

        self.learning_rate = learning_rate


    '''

    Batch Gradient Descent 

    

    1. Weights are updated considering all training examples.

    2. Learning of weights can continue for multiple iterations

    3. Learning rate needs to be defined

    '''

    def fit(self, X, y):

        rgen = np.random.RandomState(self.random_state)

        self.coef_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])

        for _ in range(self.n_iterations):

              activation_function_output = self.activation_function(self.net_input(X))

              errors = y - activation_function_output

              self.coef_[1:] = self.coef_[1:] + self.learning_rate*X.T.dot(errors)

              self.coef_[0] = self.coef_[0] + self.learning_rate*errors.sum() 

    

    '''

    Net Input is sum of weighted input signals

    '''

    def net_input(self, X):

            weighted_sum = np.dot(X, self.coef_[1:]) + self.coef_[0]

            return weighted_sum

    

    '''

    Activation function is fed the net input. As the activation function is

    an identity function, the output from activation function is same as the

    input to the function.

    '''

    def activation_function(self, X):

            return X

    

    '''

    Prediction is made on the basis of output of activation function

    '''

    def predict(self, X):

        return np.where(self.activation_function(self.net_input(X)) >= 0.0, 1, 0) 

    

    '''

    Model score is calculated based on comparison of 

    expected value and predicted value

    '''

    def score(self, X, y):

        misclassified_data_count = 0

        for xi, target in zip(X, y):

            output = self.predict(xi)

            if(target != output):

                misclassified_data_count += 1

        total_data_count = len(X)

        self.score_ = (total_data_count - misclassified_data_count)/total_data_count

        return self.score_

In [2]:
 from sklearn.datasets import load_breast_cancer
 from sklearn.model_selection import train_test_split
 import sklearn
 import numpy as np



bc = sklearn.datasets.load_breast_cancer()

X = bc.data

y = bc.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)



# Instantiate CustomPerceptron

#

adaline = CustomAdaline(n_iterations = 10)

#

# Fit the model

#

adaline.fit(X_train, y_train)

#

# Score the model

#

adaline.score(X_test, y_test)

0.6257309941520468

In [3]:
# Import necessary libraries
import numpy as np

#Adaline neural network
def Adaline(Input, Target, lr=0.2, stop=0.001):
	weight = np.random.random(Input.shape[1])
	bias = np.random.random(1)
	
	Error=[stop +1]
	# check the stop condition for the network
	while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
		error = []
		for i in range(Input.shape[0]):
			Y_input = sum(weight*Input[i]) + bias
			
			# Update the weight
			for j in range(Input.shape[1]):
				weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]

			# Update the bias
			bias=bias + lr*(Target[i]-Y_input)
			
			# Store squared error value
			error.append((Target[i]-Y_input)**2)
		# Store sum of square errors
		Error.append(sum(error))
		print('Error :',Error[-1])
	return weight, bias

# Input dataset
x = np.array([[1.0, 1.0, 1.0],
			[1.0, -1.0, 1.0],
			[-1.0, 1.0, 1.0],
			[-1.0, -1.0, -1.0]])
# Target values
t = np.array([1, 1, 1, -1])

w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)


Error : [2.5025736]
Error : [0.45962094]
Error : [0.29034608]
Error : [0.1998885]
Error : [0.13829832]
Error : [0.09571295]
Error : [0.06624173]
Error : [0.04584511]
Error : [0.03172886]
Error : [0.02195917]
Error : [0.01519768]
Error : [0.01051813]
Error : [0.00727948]
Error : [0.00503804]
Error : [0.00348677]
Error : [0.00241315]
Error : [0.00167011]
Error : [0.00115587]
Error : [0.00079996]
weight : [0.00979267 0.00979267 0.98800648]
Bias : [0.00979267]


In [4]:
# Predict from the evaluated weight and bias of adaline
def prediction(X,w,b):
	y=[]
	for i in range(X.shape[0]):
		x = X[i]
		y.append(sum(w*x)+b)
	return y
prediction(x,w,b)


[array([1.01738449]),
 array([0.99779915]),
 array([0.99779915]),
 array([-0.99779915])]

In [5]:
#Adaline neural network
import numpy as np
import pandas as pd

def activation_fn(z):
	if z>=0:
		return 1
	else:
		return -1

def Madaline(Input, Target, lr, epoch):
	weight = np.random.random((Input.shape[1],Input.shape[1]))
	bias = np.random.random(Input.shape[1])
	
	w = np.array([0.5 for i in range(weight.shape[1])])
	b = 0.5
	k = 0
	while k<epoch:
		error = []
		z_input = np.zeros(bias.shape[0])
		z = np.zeros(bias.shape[0])
		for i in range(Input.shape[0]):
			for j in range(Input.shape[1]):
				z_input[j] = sum(weight[j]*Input[i]) + bias[j]
				z[j]= activation_fn(z_input[j])

			y_input = sum(z*w) +b

			y = activation_fn(y_input)
			# Update the weight & bias
			if y != Target[i]:
				for j in range(weight.shape[1]):
					weight[j]= weight[j] + lr*(Target[i]-z_input[j])*Input[i][j]
					bias[j] = bias[j] + lr*(Target[i]-z_input[j])

			# Store squared error value
			error.append((Target[i]-z_input)**2)
		# compute sum of square error
		Error = sum(error)
		print(k,'>> Error :',Error)
		k+=1
		
	return weight, bias

# Input dataset
x = np.array([[1.0, 1.0, 1.0], [1.0, -1.0, 1.0],
			[-1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]])
# Target values
t = np.array([1, 1, 1, -1])

w,b = Madaline(x, t, 0.0001, 3)
print('weight :',w)
print('Bias :',b)


0 >> Error : [2.56295735 2.5206951  1.19337942]
1 >> Error : [2.56295735 2.5206951  1.19337942]
2 >> Error : [2.56295735 2.5206951  1.19337942]
weight : [[0.26814528 0.36718734 0.64583917]
 [0.61708602 0.53856221 0.53408792]
 [0.20272112 0.18041101 0.15916272]]
Bias : [0.92871092 0.81170839 0.29158872]


In [6]:
def prediction(X, w,b):
	y =[]
	for i in range(X.shape[0]):
		x = X[i]
		z1 = x*w
		z_1 =[]
		for j in range(z1.shape[1]):
			z_1.append(activation_fn(sum(z1[j])+b[j]))
		y_in = sum(np.array(z_1)*np.array([0.5 for j in range(w.shape[1])])) + 0.5
		y.append(activation_fn(y_in))
	return y

prediction(x, w,b)


[1, 1, 1, -1]